### ISSUE TITLE
Finished testing?

### ISSUE THREAD

**Issue by fan233** [sandertrilectronics/LWIP-FreeRTOS-Netconn-FTP-Server#1]
Hi，

Will this library work? I want to port this to my project.

**Comment by sandertrilectronics** [comment]
I have to admit that i did some bug fixes in the projects that i use this library with, but haven't uploaded them yet to this repository. I'll check what my changes are and upload them to this repository.

**Comment by fan233** [comment]
> I have to admit that i did some bug fixes in the projects that i use this library with, but haven't uploaded them yet to this repository. I'll check what my changes are and upload them to this repository.

Thank you for your response. I'm looking forward to your updates.

**Comment by sandertrilectronics** [comment]
I checked and all is already up to date! However, normally FATFS is not thread safe so a semaphore should be used for interfacing with files (in ftp_file.c functions).

**Comment by fan233** [comment]
> I checked and all is already up to date! However, normally FATFS is not thread safe so a semaphore should be used for interfacing with files (in ftp_file.c functions).

I have also tested it on my own program, and so far, I haven't encountered any issues. Thank you for your open-source contribution.
